### Step 1: Import necessary libraries

We start by importing the `pandas` library for data manipulation and `requests` for making HTTP requests to external APIs. NOTE: THIS CODE IS DIRECTLY GIVEN BY TMDB API AND print(response.text) IS JUST FOR SHOWING YOU THE DATA FOR PAGE-1.

In [115]:
import pandas as pd
import requests

### Step 2: Make an initial API request to fetch top-rated movies

We define the API endpoint URL and the necessary authorization headers. Then, we use `requests.get()` to send the request and store the response. This initial call helps us understand the API response structure before looping through all pages.

In [116]:
url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2MDk3MzcwZjE2MmE5YzIwY2NjYWJjODdiMTJmY2FlNCIsIm5iZiI6MTc3MTEzMTU5NS44MzgsInN1YiI6IjY5OTE1MmNiMWZhNmE3ZTdjYTk1OGE4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.5nBaJVfnMqpvKG6ikzsGNk7KhC9yYiOIo_gky6-c0vI"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg","genre_ids":[18,80],"id":278,"original_language":"en","original_title":"The Shawshank Redemption","overview":"Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.","popularity":30.8191,"poster_path":"/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg","release_date":"1994-09-23","title":"The Shawshank Redemption","video":false,"vote_average":8.716,"vote_count":29721},{"adult":false,"backdrop_path":"/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg","genre_ids":[18,80],"id":238,"original_language":"en","original_title":"The Godfather","overview":"Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.","popularity":36.4215,"poster_path":"/3bhkrj58Vtu7enYsRolD1fZdja1.jpg","release_date":"1972-03-14","title":"The Godfather","video":false,"vote_average":8.687,"vote_count":22451},{"adult":false,"backdrop_path":"/kGzFbGhp99zva6oZODW5atUtnqi.jpg","genre_ids":[18,80],"id":240,"original_language":"en","original_title":"The Godfather Part II","overview":"In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.","popularity":17.5941,"poster_path":"/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg","release_date":"1974-12-20","title":"The Godfather Part II","video":false,"vote_average":8.571,"vote_count":13586},{"adult":false,"backdrop_path":"/zb6fM1CX41D9rF9hdgclu0peUmy.jpg","genre_ids":[18,36,10752],"id":424,"original_language":"en","original_title":"Schindler's List","overview":"The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.","popularity":18.6937,"poster_path":"/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg","release_date":"1993-12-15","title":"Schindler's List","video":false,"vote_average":8.567,"vote_count":17106},{"adult":false,"backdrop_path":"/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg","genre_ids":[18],"id":389,"original_language":"en","original_title":"12 Angry Men","overview":"The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.","popularity":13.0084,"poster_path":"/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg","release_date":"1957-04-10","title":"12 Angry Men","video":false,"vote_average":8.555,"vote_count":9741},{"adult":false,"backdrop_path":"/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg","genre_ids":[16,10751,14],"id":129,"original_language":"ja","original_title":"千と千尋の神隠し","overview":"A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.","popularity":20.4629,"poster_path":"/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg","release_date":"2001-07-20","title":"Spirited Away","video":false,"vote_average":8.534,"vote_count":17949},{"adult":false,"backdrop_path":"/dqK9Hag1054tghRQSqLSfrkvQnA.jpg","genre_ids":[28,80,53],"id":155,"original_language":"en","original_title":"The Dark Knight","overview":"Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.","popularity":30.9861,"poster_path":"/qJ2tW6WMUDux911r6m7haRef0WH.jpg","release_date":"2008-07-16","title":"The Dark Knight","video":false,"vote_average":8.526,"vote_count":35172},{"adult":false,"backdrop_path":"/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg","genre_ids":[35,18,10749],"id":19404,"original_language":"hi","original_title":"दिलवाले दुल्हनिया ले जायेंगे","overview":"Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.","popularity":6.4929,"poster_path":"/2CAL2433ZeIihfX1Hb2139CX0pW.jpg","release_date":"1995-10-20","title":"Dilwale Dulhania Le Jayenge","video":false,"vote_average":8.516,"vote_count":4554},{"adult":false,"backdrop_path":"/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg","genre_ids":[14,18,80],"id":497,"original_language":"en","original_title":"The Green Mile","overview":"A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.","popularity":20.4923,"poster_path":"/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg","release_date":"1999-12-10","title":"The Green Mile","video":false,"vote_average":8.504,"vote_count":18848},{"adult":false,"backdrop_path":"/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg","genre_ids":[35,53,18],"id":496243,"original_language":"ko","original_title":"기생충","overview":"All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.","popularity":18.2958,"poster_path":"/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg","release_date":"2019-05-30","title":"Parasite","video":false,"vote_average":8.495,"vote_count":20129},{"adult":false,"backdrop_path":"/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg","genre_ids":[12,14,28],"id":122,"original_language":"en","original_title":"The Lord of the Rings: The Return of the King","overview":"As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​","popularity":30.1025,"poster_path":"/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg","release_date":"2003-12-17","title":"The Lord of the Rings: The Return of the King","video":false,"vote_average":8.493,"vote_count":26020},{"adult":false,"backdrop_path":"/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg","genre_ids":[53,80,35],"id":680,"original_language":"en","original_title":"Pulp Fiction","overview":"A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.","popularity":23.9774,"poster_path":"/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg","release_date":"1994-09-10","title":"Pulp Fiction","video":false,"vote_average":8.486,"vote_count":29678},{"adult":false,"backdrop_path":"/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg","genre_ids":[16,10749,18],"id":372058,"original_language":"ja","original_title":"君の名は。","overview":"High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.","popularity":17.7326,"poster_path":"/q719jXXEzOoYaps6babgKnONONX.jpg","release_date":"2016-08-26","title":"Your Name.","video":false,"vote_average":8.479,"vote_count":12290},{"adult":false,"backdrop_path":"/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg","genre_ids":[37],"id":429,"original_language":"it","original_title":"Il buono, il brutto, il cattivo","overview":"While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.","popularity":15.062,"poster_path":"/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg","release_date":"1966-12-22","title":"The Good, the Bad and the Ugly","video":false,"vote_average":8.468,"vote_count":9409},{"adult":false,"backdrop_path":"/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg","genre_ids":[12,18,878],"id":157336,"original_language":"en","original_title":"Interstellar","overview":"The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.","popularity":46.8378,"poster_path":"/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg","release_date":"2014-11-05","title":"Interstellar","video":false,"vote_average":8.467,"vote_count":38859},{"adult":false,"backdrop_path":"/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg","genre_ids":[35,18,10749],"id":13,"original_language":"en","original_title":"Forrest Gump","overview":"A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.","popularity":24.6044,"poster_path":"/saHP97rTPS5eLmrLQEcANmKrsFl.jpg","release_date":"1994-06-23","title":"Forrest Gump","video":false,"vote_average":8.462,"vote_count":29235},{"adult":false,"backdrop_path":"/gILte6Zd7m1YneIr6MVhh30S9pr.jpg","genre_ids":[18,80],"id":769,"original_language":"en","original_title":"GoodFellas","overview":"The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.","popularity":25.2771,"poster_path":"/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg","release_date":"1990-09-12","title":"GoodFellas","video":false,"vote_average":8.452,"vote_count":14010},{"adult":false,"backdrop_path":"/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg","genre_ids":[28,18],"id":346,"original_language":"ja","original_title":"七人の侍","overview":"A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.","popularity":9.8256,"poster_path":"/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg","release_date":"1954-04-26","title":"Seven Samurai","video":false,"vote_average":8.451,"vote_count":4111},{"adult":false,"backdrop_path":"/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg","genre_ids":[16,18,10752],"id":12477,"original_language":"ja","original_title":"火垂るの墓","overview":"In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.","popularity":0.0089,"poster_path":"/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg","release_date":"1988-04-16","title":"Grave of the Fireflies","video":false,"vote_average":8.443,"vote_count":6353},{"adult":false,"backdrop_path":"/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg","genre_ids":[35,18],"id":637,"original_language":"it","original_title":"La vita è bella","overview":"A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.","popularity":9.4178,"poster_path":"/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg","release_date":"1997-12-20","title":"Life Is Beautiful","video":false,"vote_average":8.44,"vote_count":13783}],"total_pages":533,"total_results":10660}

### Step 3: Display the response object

This shows the status of the HTTP request, confirming if it was successful (e.g., `<Response [200]>` indicates success).

In [117]:
response

### Step 4: Parse the API response into JSON

We convert the raw HTTP response content into a Python dictionary or list using `.json()`, making the data accessible for processing.

In [118]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 30.8191,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.716,
   'vote_count': 29721},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 36.4215,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.687,
   'vote_count': 22451},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 17.5941,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.571,
   'vote_count': 13586},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 18.6937,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.567,
   'vote_count': 17106},
  {'adult': False,
   'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 13.0084,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.555,
   'vote_count': 9741},
  {'adult': False,
   'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 20.4629,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.534,
   'vote_count': 17949},
  {'adult': False,
   'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 30.9861,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.526,
   'vote_count': 35172},
  {'adult': False,
   'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 6.4929,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.516,
   'vote_count': 4554},
  {'adult': False,
   'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 20.4923,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.504,
   'vote_count': 18848},
  {'adult': False,
   'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 18.2958,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.495,
   'vote_count': 20129},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 30.1025,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.493,
   'vote_count': 26020},
  {'adult': False,
   'backdrop_path': '/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 23.9774,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.486,
   'vote_count': 29678},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 17.7326,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.479,
   'vote_count': 12290},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 15.062,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.468,
   'vote_count': 9409},
  {'adult': False,
   'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 46.8378,
   'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
   'release_date': '2014-11-05',
   'title': 'Interstellar',
   'video': False,
   'vote_average': 8.467,
   'vote_count': 38859},
  {'adult': False,
   'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 24.6044,
   'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.462,
   'vote_count': 29235},
  {'adult': False,
   'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 25.2771,
   'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.452,
   'vote_count': 14010},
  {'adult': False,
   'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 9.8256,
   'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.451,
   'vote_count': 4111},
  {'adult': False,
   'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.0089,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.443,
   'vote_count': 6353},
  {'adult': False,
   'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg',
   'genre_ids': [35, 18],
   'id': 637,
   'original_language': 'it',
   'original_title': 'La vita è bella',
   'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
   'popularity': 9.4178,
   'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
   'release_date': '1997-12-20',
   'title': 'Life Is Beautiful',
   'video': False,
   'vote_average': 8.44,
   'vote_count': 13783}],
 'total_pages': 533,
 'total_results': 10660}

### Step 5: Extract the 'results' key from the JSON response

The actual movie data is typically nested under a 'results' key in the API response. We extract this list of movie dictionaries.

In [119]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 30.8191,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.716,
  'vote_count': 29721},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 36.4215,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.687,
  'vote_count': 22451},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 17.5941,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather Part II',
  'video': False,
  'vote_average': 8.571,
  'vote_count': 13586},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 18.6937,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.567,
  'vote_count': 17106},
 {'adult': False,
  'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
  'genre_ids': [18],
  'id': 389,
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 13.0084,
  'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
  'release_date': '1957-04-10',
  'title': '12 Angry Men',
  'video': False,
  'vote_average': 8.555,
  'vote_count': 9741},
 {'adult': False,
  'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 20.4629,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'title': 'Spirited Away',
  'video': False,
  'vote_average': 8.534,
  'vote_count': 17949},
 {'adult': False,
  'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 30.9861,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'title': 'The Dark Knight',
  'video': False,
  'vote_average': 8.526,
  'vote_count': 35172},
 {'adult': False,
  'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 6.4929,
  'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
  'release_date': '1995-10-20',
  'title': 'Dilwale Dulhania Le Jayenge',
  'video': False,
  'vote_average': 8.516,
  'vote_count': 4554},
 {'adult': False,
  'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 20.4923,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'title': 'The Green Mile',
  'video': False,
  'vote_average': 8.504,
  'vote_count': 18848},
 {'adult': False,
  'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 18.2958,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'title': 'Parasite',
  'video': False,
  'vote_average': 8.495,
  'vote_count': 20129},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 30.1025,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'title': 'The Lord of the Rings: The Return of the King',
  'video': False,
  'vote_average': 8.493,
  'vote_count': 26020},
 {'adult': False,
  'backdrop_path': '/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 23.9774,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'title': 'Pulp Fiction',
  'video': False,
  'vote_average': 8.486,
  'vote_count': 29678},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 17.7326,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'title': 'Your Name.',
  'video': False,
  'vote_average': 8.479,
  'vote_count': 12290},
 {'adult': False,
  'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
  'genre_ids': [37],
  'id': 429,
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 15.062,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-22',
  'title': 'The Good, the Bad and the Ugly',
  'video': False,
  'vote_average': 8.468,
  'vote_count': 9409},
 {'adult': False,
  'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 46.8378,
  'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  'release_date': '2014-11-05',
  'title': 'Interstellar',
  'video': False,
  'vote_average': 8.467,
  'vote_count': 38859},
 {'adult': False,
  'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 13,
  'original_language': 'en',
  'original_title': 'Forrest Gump',
  'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
  'popularity': 24.6044,
  'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
  'release_date': '1994-06-23',
  'title': 'Forrest Gump',
  'video': False,
  'vote_average': 8.462,
  'vote_count': 29235},
 {'adult': False,
  'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
  'genre_ids': [18, 80],
  'id': 769,
  'original_language': 'en',
  'original_title': 'GoodFellas',
  'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
  'popularity': 25.2771,
  'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
  'release_date': '1990-09-12',
  'title': 'GoodFellas',
  'video': False,
  'vote_average': 8.452,
  'vote_count': 14010},
 {'adult': False,
  'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
  'genre_ids': [28, 18],
  'id': 346,
  'original_language': 'ja',
  'original_title': '七人の侍',
  'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
  'popularity': 9.8256,
  'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
  'release_date': '1954-04-26',
  'title': 'Seven Samurai',
  'video': False,
  'vote_average': 8.451,
  'vote_count': 4111},
 {'adult': False,
  'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg',
  'genre_ids': [16, 18, 10752],
  'id': 12477,
  'original_language': 'ja',
  'original_title': '火垂るの墓',
  'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
  'popularity': 0.0089,
  'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
  'release_date': '1988-04-16',
  'title': 'Grave of the Fireflies',
  'video': False,
  'vote_average': 8.443,
  'vote_count': 6353},
 {'adult': False,
  'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg',
  'genre_ids': [35, 18],
  'id': 637,
  'original_language': 'it',
  'original_title': 'La vita è bella',
  'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
  'popularity': 9.4178,
  'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
  'release_date': '1997-12-20',
  'title': 'Life Is Beautiful',
  'video': False,
  'vote_average': 8.44,
  'vote_count': 13783}]

### Step 6: Display the temporary DataFrame

This step allows us to preview the structure and content of the DataFrame created from a single page's API response.

In [120]:
temp_df = pd.DataFrame(response.json()['results'])

### Step 7: Re-create a temporary DataFrame with a different set of selected columns

This adjusts the columns selected from the API response for better data representation in the DataFrame.

In [121]:
temp_df = pd.DataFrame(response.json()['results'])[['genre_ids','id','original_language','overview','popularity','release_date','title','vote_average','vote_count']]

In [122]:
temp_df

,genre_ids,id,original_language,overview,popularity,release_date,title,vote_average,vote_count
0,"[18, 80]",278,en,Imprisoned in the 1940s for the double murder ...,30.8191,1994-09-23,The Shawshank Redemption,8.716,29721
1,"[18, 80]",238,en,"Spanning the years 1945 to 1955, a chronicle o...",36.4215,1972-03-14,The Godfather,8.687,22451
2,"[18, 80]",240,en,In the continuing saga of the Corleone crime f...,17.5941,1974-12-20,The Godfather Part II,8.571,13586
3,"[18, 36, 10752]",424,en,The true story of how businessman Oskar Schind...,18.6937,1993-12-15,Schindler's List,8.567,17106
4,[18],389,en,The defense and the prosecution have rested an...,13.0084,1957-04-10,12 Angry Men,8.555,9741
5,"[16, 10751, 14]",129,ja,"A young girl, Chihiro, becomes trapped in a st...",20.4629,2001-07-20,Spirited Away,8.534,17949
6,"[28, 80, 53]",155,en,Batman raises the stakes in his war on crime. ...,30.9861,2008-07-16,The Dark Knight,8.526,35172
7,"[35, 18, 10749]",19404,hi,"Raj is a rich, carefree, happy-go-lucky second...",6.4929,1995-10-20,Dilwale Dulhania Le Jayenge,8.516,4554
8,"[14, 18, 80]",497,en,A supernatural tale set on death row in a Sout...,20.4923,1999-12-10,The Green Mile,8.504,18848
9,"[35, 53, 18]",496243,ko,"All unemployed, Ki-taek's family takes peculia...",18.2958,2019-05-30,Parasite,8.495,20129
10,"[12, 14, 28]",122,en,As armies mass for a final battle that will de...,30.1025,2003-12-17,The Lord of the Rings: The Return of the King,8.493,26020
11,"[53, 80, 35]",680,en,"A burger-loving hit man, his philosophical par...",23.9774,1994-09-10,Pulp Fiction,8.486,29678
12,"[16, 10749, 18]",372058,ja,High schoolers Mitsuha and Taki are complete s...,17.7326,2016-08-26,Your Name.,8.479,12290
13,[37],429,it,While the Civil War rages on between the Union...,15.0620,1966-12-22,"The Good, the Bad and the Ugly",8.468,9409
14,"[12, 18, 878]",157336,en,The adventures of a group of explorers who mak...,46.8378,2014-11-05,Interstellar,8.467,38859
15,"[35, 18, 10749]",13,en,A man with a low IQ has accomplished great thi...,24.6044,1994-06-23,Forrest Gump,8.462,29235
16,"[18, 80]",769,en,"The true story of Henry Hill, a half-Irish, ha...",25.2771,1990-09-12,GoodFellas,8.452,14010
17,"[28, 18]",346,ja,A samurai answers a village's request for prot...,9.8256,1954-04-26,Seven Samurai,8.451,4111
18,"[16, 18, 10752]",12477,ja,"In the final months of World War II, 14-year-o...",0.0089,1988-04-16,Grave of the Fireflies,8.443,6353
19,"[35, 18]",637,it,A touching story of an Italian book seller of ...,9.4178,1997-12-20,Life Is Beautiful,8.440,13783

In [123]:
df = pd.DataFrame()

In [124]:
df

Empty DataFrame
Columns: []
Index: []

### Step 8: Loop through API pages to collect all movie data

This loop iterates from page 1 up to the maximum valid page (500 in this case, based on the API's limitation). For each page, it makes an API request, parses the JSON response, extracts movie data, and appends it to our main DataFrame (`df`). It also includes error handling for cases where the 'results' key might be missing (e.g., when an invalid page number is requested).

IT WAS GIVING ERROR ON RESULTS AS PAGES AFTER 500 DIDN'T CONTAIN RESULTS

In [125]:
for i in range (1,553):
    url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={}".format(i)
    headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2MDk3MzcwZjE2MmE5YzIwY2NjYWJjODdiMTJmY2FlNCIsIm5iZiI6MTc3MTEzMTU5NS44MzgsInN1YiI6IjY5OTE1MmNiMWZhNmE3ZTdjYTk1OGE4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.5nBaJVfnMqpvKG6ikzsGNk7KhC9yYiOIo_gky6-c0vI"
    }
    response = requests.get(url, headers=headers)
    response_json = response.json()
    if 'results' in response_json:
        temp_df = pd.DataFrame(response_json['results'])[['genre_ids','id','original_language','overview','popularity','release_date','title','vote_average','vote_count']]
        df = pd.concat([df, temp_df], ignore_index=True)
    else:
        print(f"Warning: 'results' key not found in response for page {i}. Response content: {response_json}")
        # Optionally, you can break the loop or handle this case differently
        break # Breaking the loop as an example, you might want to continue or log this.

Warning: 'results' key not found in response for page 501. Response content: {'success': False, 'status_code': 22, 'status_message': 'Invalid page: Pages start at 1 and max at 500. They are expected to be an integer.'}

In [126]:
df

,genre_ids,id,original_language,overview,popularity,release_date,title,vote_average,vote_count
0,"[18, 80]",278,en,Imprisoned in the 1940s for the double murder ...,30.8191,1994-09-23,The Shawshank Redemption,8.716,29721
1,"[18, 80]",238,en,"Spanning the years 1945 to 1955, a chronicle o...",36.4215,1972-03-14,The Godfather,8.687,22451
2,"[18, 80]",240,en,In the continuing saga of the Corleone crime f...,17.5941,1974-12-20,The Godfather Part II,8.571,13586
3,"[18, 36, 10752]",424,en,The true story of how businessman Oskar Schind...,18.6937,1993-12-15,Schindler's List,8.567,17106
4,[18],389,en,The defense and the prosecution have rested an...,13.0084,1957-04-10,12 Angry Men,8.555,9741
...,...,...,...,...,...,...,...,...,...
9995,"[27, 35]",10012,en,A werewolf loose in Los Angeles changes the li...,2.1952,2005-02-25,Cursed,5.400,757
9996,"[28, 53, 80]",480042,en,After security expert Ray Breslin is hired to ...,2.5912,2019-06-20,Escape Plan: The Extractors,5.400,921
9997,"[27, 9648]",465086,en,After a young mother murders her family in her...,5.0642,2019-12-31,The Grudge,5.400,1295
9998,"[35, 53]",276839,en,"Don Champagne seems to have it all, but when h...",1.4147,2015-03-13,Home Sweet Hell,5.423,490
9999,"[12, 10751, 35, 14]",39346,en,Before he met and befriended the other ghouls ...,2.1617,1997-09-09,Casper: A Spirited Beginning,5.400,330

### Step 9: Display the shape of the final DataFrame

This shows the number of rows (movies) and columns (attributes) in our comprehensive dataset, confirming how much data was successfully collected.

In [127]:
df.shape

(10000, 9)

In [128]:
df.to_csv('movies.csv')